cask_args appdir: "/Applications"

# Tap Homebrew
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

# System
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "mas"
brew "curl"
brew "wget"
brew "git"
brew "openssl"
brew "coreutils"
brew "moreutils"
brew "findutils"
brew "binutils"
brew "rename"
brew "tree"
brew "htop"
brew "pidof"
brew "pstree"
brew "grep"
brew "openssh"
brew "rsync"
brew "ssh-copy-id"
brew "screen"
brew "gmp"
brew "nmap"
brew "rlwrap"
brew "sslscan"

# Images, Audio, Video
brew "gifify"
brew "ffmpeg"

# Dev
brew "ruby"
brew "rust"
brew "node"
brew "yarn"
brew "python"
brew "pyenv"
brew "asdf"
brew "redis"
brew "jq"

# Ops
brew "kind"
brew "docker-compose"
brew "podman"
brew "helm"
brew "kubernetes-cli"
brew "terraform"
brew "kubectx"
brew "circleci"
brew "awscli"
brew "serverless"

# Casks
cask "visual-studio-code"
cask "raycast"
cast "bitwarden"
cask "google-chrome"
cask "firefox"
cask "rectangle"
cask "gitup"
cask "postman"
cask "wireshark"
cask "gimp"
cask "inkscape"
cask "handbrake"
cask "slack"
cask "spotify"
cask "notion"
cask "zoom"
cask "alfred"
cask "vlc"
cask "webtorrent"